Toolio/Toolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('user/', include(('user.urls', 'user'), namespace='user')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Toolio/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('createAd/', views.createAd, name="createAd"),
    path('userPage/<int:user_id>', views.userPage, name="userPage"),
    path("edit_ad/<int:ad_id>/", views.edit_ad, name="edit_ad"),
    path('delete/<int:ad_id>/', views.delete_ad, name='delete_ad'),
    path('confirmBooking/<int:ad_id>/', views.confirm_booking, name='confirmBooking'),
    path('rate_user/<int:user_id>/', views.rate_user, name='rate_user'),
    path('create_custom_list/<int:user_id>', views.create_custom_list, name='create_custom_list'),
    path('save_ad_to_list/<int:user_id>', views.save_ad_to_list, name='save_ad_to_list'),
]

Toolio/user/urls.py
from django.urls import path 
from .views import register, log_in, log_out

urlpatterns = [
  path('register/', register, name="register"),
  path('login/', log_in, name="login"),
  path('logout/', log_out, name="logout"),
]

Toolio/main/models.py
import django.utils.timezone
from django.db import models
from user.models import CustomUser

# Create your models here.
class ad(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="advertisement", null=True)
        
    isRequest = models.BooleanField(default="False")
    isRented = models.BooleanField(default="False")
    title = models.CharField(max_length=100, default="")
    category = models.CharField(max_length=100, default="Annet")
    date = models.DateField(default=django.utils.timezone.now)
    price = models.IntegerField(default=0)
    description = models.CharField(max_length=500, default="")
    image = models.ImageField(upload_to='images/')
    

    def __str__(self):
        return self.title

class CustomList(models.Model):
    title = models.CharField(max_length=100, default="")
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="custom_list")

class adInList(models.Model):
    customList = models.ForeignKey(CustomList, on_delete=models.CASCADE, related_name="in_list")
    savedAd = models.ForeignKey(ad, on_delete=models.CASCADE, related_name="saved_ad")

Toolio/main/forms.py
from django import forms
from django.forms import widgets

from .models import ad, CustomList

# Define the available ad types.
AD_TYPES = [
    ("normalAd", "Annonse"),
    ("requestAd", "Ønskes leid")
]

# Define the available categories.
options = [
    ("Annet", "Annet"),
    ("Snekring og tømrerarbeid", "Snekring og tømrerarbeid"),
    ("Maling og overflatebehandling", "Maling og overflatebehandling"),
    ("Hagearbeid", "Hagearbeid"),   
    ("Rørleggerarbeid", "Rørleggerarbeid"),
    ("Elektrikerarbeid", "Elektrikerarbeid"),
    ("Bilreperasjon", "Bilrepereasjon"),
    ("Møbelmontering", "Møbelmontering"),
    ("Gulvlegging", "Gulvlegging"),
    ("Rengjøring", "Rengjøring")
]

# Define a custom widget for the date input field.
class DateInput(forms.DateInput):
    input_type = "date"

# Define a form for creating an ad.
class createAdForm(forms.ModelForm):
    type = forms.ChoiceField(choices=AD_TYPES, widget=forms.RadioSelect(attrs={"onchange":"changeForm(this.id)"}))
    title = forms.CharField(label="Tittel", max_length=100, widget=forms.TextInput(attrs={"placeholder": "Toolio"}), label_suffix='')
    category = forms.ChoiceField(label = "Kategori", choices = options)
    date = forms.DateField(widget=DateInput(), label="Produktet er ledig frem til")
    price = forms.IntegerField(label="Pris", widget=widgets.NumberInput(attrs={"style":"border-radius: 0 !important;"}),min_value=0)
    description = forms.CharField(label="Beskrivelse", widget=forms.Textarea(attrs={"placeholder": "Beskriv verktøyet", "rows": 3}), max_length=500, label_suffix='')
    image = forms.FileField(label="Bilde av redskapet", required=False, label_suffix='')

    class Meta:
        model = ad
        fields = ['type', 'title', 'category', 'date', 'price', 'description', 'image']

# Define a form for editing an ad.
class editAdForm(forms.ModelForm):
    # Define the form fields.
    title = forms.CharField(label="Tittel", max_length=100, label_suffix='')
    category = forms.ChoiceField(label = "Katerogi", choices = options)
    date = forms.DateField(widget=DateInput(), label="Produktet er ledig frem til",label_suffix='')
    price = forms.IntegerField(label="Pris", widget=widgets.NumberInput(attrs={"style":"border-radius: 0 !important;"}), label_suffix='', min_value=0)
    description = forms.CharField(label="Beskrivelse",widget=forms.Textarea(attrs={'rows': 5, 'cols': 40}), max_length=500, label_suffix='')
    image = forms.FileField(label="Bilde av redskapet", required=False, label_suffix='')
    isRented = forms.BooleanField(widget=forms.CheckboxInput, label="Utleid", required=False, label_suffix='')

    class Meta:
        model = ad
        fields = ('title', 'category', 'date', 'price','description',  'image', 'isRented')

# Define a form for editing a "ønsket leid" ad.
class editAdFormWanted(forms.ModelForm):
    # Define the form fields.
    title = forms.CharField(label="Tittel", max_length=100, label_suffix='')
    category = forms.ChoiceField(label = "Katerogi", choices = options)
    date = forms.DateField(widget=DateInput(), label="Ønsker å leie til",label_suffix='')
    price = forms.IntegerField(label="Budsjett", widget=widgets.NumberInput(attrs={"style":"border-radius: 0 !important;"}), label_suffix='', min_value=0)
    description = forms.CharField(label="Beskrivelse",widget=forms.Textarea(attrs={'rows': 5, 'cols': 40}), max_length=500, label_suffix='')
    
    class Meta:
        model = ad
        fields = ('title', 'category', 'date', 'price','description')


class confirmBooking(forms.ModelForm):
    isRented = forms.BooleanField(initial=True, widget=forms.CheckboxInput, label="Utleid", required=False, label_suffix='')
    
    class Meta:
        model = ad 
        fields = ('isRented',)


class createCustomListForm(forms.ModelForm):
    title = forms.CharField(label="Tittel", max_length=100, label_suffix='', widget=forms.TextInput)
    
    class Meta:
        model = CustomList
        fields = ['title']

Toolio/main/views.py
from .models import ad, CustomList, adInList
from user.models import CustomUser, Interaction, Interaction
from django.shortcuts import render, get_object_or_404, redirect
from .forms import createAdForm, editAdForm, editAdFormWanted, confirmBooking, createCustomListForm, confirmBooking
from django.contrib.auth.decorators import login_required
from django.conf import settings
from user.find_distance import get_ad_distance_dict

# Create your views here.

def home(request):
    context = {
        'adList': ad.objects.all()
    }
    
    if request.user.is_authenticated:
        ad_distance_dict = get_ad_distance_dict(request.user)
        context['ad_distance_dict'] = ad_distance_dict

    return render(request, "main/home.html", context)


def confirm_booking(request, ad_id):
    ad_instance= get_object_or_404(ad, id=ad_id)
    ad_instance.isRented = True
    ad_instance.save()
    
    interaction = Interaction.objects.update_or_create(
        a=request.user,
        b=ad_instance.user,
    )
    interaction[0].rated_a = False
    interaction[0].rated_b = False
    interaction[0].save()
    
    
    return redirect('home')


def get_user_average_rating(user):
    b=True
    interactions = Interaction.objects.filter(b_id=user.id, rating_b__gt=0).exclude(rating_b__isnull=True)
        
    if interactions.count() == 0:
        interactions = Interaction.objects.filter(a_id=user.id, rating_a__gt=0).exclude(rating_a__isnull=True)
        b=False

    if interactions.count() == 0:
        return None

    if b:
        total_rating = sum(interaction.rating_b for interaction in interactions)

    else:
        total_rating = sum(interaction.rating_a for interaction in interactions)

    return total_rating / interactions.count()


def userPage(request, user_id):
    profile_user = CustomUser.objects.get(id=user_id)
    average_rating = get_user_average_rating(profile_user)
    list_form = createCustomListForm()
    ad_distance_dict = get_ad_distance_dict(request.user)
       
    
    context = {
        'profile_user': profile_user,
        'average_rating': average_rating,
        'form': list_form,
         'ad_distance_dict': ad_distance_dict
    }
    return render(request, 'main/userPage.html', context)

def rate_user(request, user_id):
    rated_user = CustomUser.objects.get(id=user_id) #b
    user = request.user #a
    b = True
    
    # Check if an interaction record exists between the borrower and the lender
    interaction = Interaction.objects.filter(a=user, b=rated_user, rated_b=False).first()
    
    # Retrieve the ad object associated with the booking
    ad_obj = ad.objects.filter(isRented=True, user=rated_user).first()

    if interaction==None:
        interaction = Interaction.objects.filter(b=user, a=rated_user, rated_a=False).first()
        print(interaction)
        ad_obj = ad.objects.filter(isRented=True, user=user).first()
        b = False
  
    if request.method == "POST":
        # Check if the user has confirmed the booking and if an interaction record exists
        if ad_obj and interaction and b:
            rating = int(request.POST["rating"])
            interaction.rating_b = rating
            interaction.rated_b = True
            interaction.save()
            return redirect('userPage', user_id)
        elif ad_obj and interaction:
            rating = int(request.POST["rating"])
            interaction.rating_a = rating
            interaction.rated_a = True
            interaction.save()
            return redirect('userPage', user_id)
        else:
            print("         __")
            print("        / _)")
            print(" .-^^^-/ /")
            print("(_,____/   ")

   
    return redirect('userPage', user_id)

@login_required(login_url=settings.LOGIN_URL)
def createAd(request):
    if request.method == "POST":
        form = createAdForm(request.POST, request.FILES)

        if form.is_valid():
            type = form.cleaned_data["type"]
            #title = form.cleaned_data["title"]
            #date = form.cleaned_data["date"]
            #price = form.cleaned_data["price"]
            #description = form.cleaned_data["description"]
            #image = form.cleaned_data["image"]
            if (type == "requestAd"):
                isRequest = True
            else:
                isRequest = False

            newAd = form.save(commit=False)
            newAd.user = request.user

            newAd.isRequest = isRequest
            newAd.save()
            #newAd = ad(isRequest=isRequest, title=title, date=date, price=price, description=description, image=image)
            # newAd.save()
            # request.user.advertisement.add(newAd)

        return redirect("/")

    else:
        form = createAdForm()
    return render(request, "main/createAd.html", {"form": form})


def edit_ad(request, ad_id):
    ad_to_edit = get_object_or_404(ad, id=ad_id)

    if ad_to_edit.isRequest:  # Different classes for editing "annonse" and editing "ønskes leid"
        form_class = editAdFormWanted
    else:
        form_class = editAdForm

    if request.method == 'POST':
        form = form_class(request.POST, request.FILES, instance=ad_to_edit)
        if form.is_valid():
            ad_obj = form.save(commit=True)
            return redirect('/')
    else:
        form = form_class(instance=ad_to_edit)
    return render(request, 'main/editAd.html', {'form': form, 'ad': ad_to_edit})


def delete_ad(request, ad_id):
    # use the model class Ad to retrieve the object
    ad_obj = get_object_or_404(ad, id=ad_id)
    ad_obj.delete()
    return redirect('home')  # redirect to the home page

def create_custom_list(request, user_id):
    if request.method == "POST":
        form = createCustomListForm(request.POST)

        if form.is_valid():
            newList = form.save(commit=False)
            newList.user = request.user
            newList.save()
        return redirect("/")

    else:
        form = createCustomListForm()
    return redirect('userPage', request.user)

def save_ad_to_list(request, user_id):
    ad_id = request.POST["ad_id"]
    list_id = request.POST["list_id"]
    ad_to_save = ad.objects.get(pk=ad_id)
    list_to_add = CustomList.objects.get(pk=list_id)
    
    saved_ad_to_list, created = adInList.objects.get_or_create(
        customList = list_to_add,
        savedAd = ad_to_save
    )
    print(f'\n Ad: {saved_ad_to_list.savedAd.title} to the list: {saved_ad_to_list.customList.title}\n')
    
    return redirect('userPage', request.user.id)

Toolio/main/templates/main/base.html
<!doctype html>
<html>
    <head>
        <title>{% block title %}Toolio{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <style>
            body {
                padding: 3em 3em 6em 3em;
            }

            main {
                margin: 3em;
                min-height: 60%;
            }

            .navbar {
                background-color: #ffa541 !important;
            }

            .navbar-menu {
                display: flex;
                flex-direction: row;
                justify-content: space-evenly;
                width: 25%;
                align-items: center;
            }

            .default-button {
                background-color: #3bd09c !important;
                color: white !important;
            }

            .default-button:hover {
                background-color: #4db38f !important;
            }


            /* Light Theme */
            body.light {
                background-color: #ffdbb3 !important;
            }

            /* Dark Theme */
            body.dark {
                background-color: #2d2d2d !important;
                color: #fff !important;
            } /* #9b59b6 */

            body.dark h1, body.dark h2, body.dark .support a, body.dark p, body.dark label, body.dark h5, body.dark h6{
                color: #fff !important;
            }

            body.dark .card {
                background-color: #3a3a3a !important;
            }

            body.dark input {
                background: #4a4a4a !important;
                color: #fff !important;
                border: none;
            }

            body.dark .card-subtitle {
                color: #aaa !important;
            }

            body.dark input::placeholder { /* Chrome, Firefox, Opera, Safari 10.1+ */
                color: #aaa;
                opacity: 1; /* Firefox */
            }

            body.dark .popup {
                background: #4a4a4a !important;
            }


            /* Dark/Light mode */
            .toggle-button {
                background-color: #4CAF50;
                color: white;
                padding: 8px 16px;
                border: none;
                cursor: pointer;
                font-size: 14px;
                border-radius: 4px;
            }

            .toggle-button:hover {
              background-color: #3e8e41;
            }

            .checkbox {
                opacity: 0;
                position: absolute;
              }
  
            .checkbox-label {
                background-color: #111;
                width: 50px;
                height: 26px;
                border-radius: 50px;
                position: relative;
                padding: 5px;
                cursor: pointer;
                display: flex;
                justify-content: space-between;
                align-items: center;
            }
  
            .fa-moon {
                background-image: url('../../static/media/moon.svg');
                width: 20px;
                height: 20px;
                background-repeat: no-repeat;
            }
  
            .fa-sun {
                background-image: url('../../static/media/sun.svg');
                width: 17px;
                height: 17px;
                background-repeat: no-repeat;
            }
  
            .checkbox-label .ball {
                background-color: #fff;
                width: 22px;
                height: 22px;
                position: absolute;
                left: 2px;
                top: 2px;
                border-radius: 50%;
                transition: transform 0.2s linear;
            }
  
            .checkbox:checked + .checkbox-label .ball {
                transform: translateX(24px);
            }



            /* Popup */
            .popup {
                width: 400px;
                background: #fff;
                border-radius: 6px;
                position: absolute;
                top: 0;
                left: 50%;
                transform: translate(-50%, -50%) scale(0.1);
                text-align: left;
                padding: 30px;
                color: #333;
                visibility: hidden;
                transition: transform 0.4s, top 0.4s; 
                display: inline-block;
                z-index: 2;
            }

            .open-popup {
                visibility: visible;
                top: 50%;
                transform: translate(-50%, -50%) scale(1);
                position: fixed;
            }

            #closebutton {
                cursor: pointer;
                border: none;
                font-weight: 700;
                font-size: 1.5em;
                transform: translate(10px, -20px);
                padding: 0.5rem 0.7rem;
                background: #eee !important;
                border-radius: 50%;
                position: absolute;
                top: 30px;
                right: 30px;
                color: #000 !important;
                box-shadow: none !important;
            }

            .popup button{
                background-color: #4CAF50; /* Green */
                border: none;
                color: white;
                padding: 15px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
            }

            .overlay {
                position: fixed;
                top: 0;
                bottom: 0;
                left: 0;
                right: 0;
                width: 100%;
                height: 100%;
                background: rgba(0, 0, 0, 0.02);
                backdrop-filter: blur(3px);
                z-index: 1;
            }

            .hidden {
                display: none;
            }

            /* Footer */
            .footer {
                background-color: #211b31;
                padding: 2em 0em 2em 0em;
            }
              
            .footer ul {
                padding:0;
                list-style:none;
                text-align:center;
                font-size:18px;
                line-height:1.6;
                margin-bottom:0;
            }
              
            .footer li {
                padding:0 10px;
            }
              
            .footer ul a {
                color: #f7e7ce;
                text-decoration:none;
                opacity:0.8;
            }
              
            .footer ul a:hover {
                opacity:1;
            }
              
            .footer .copyright {
                margin-top:15px;
                text-align:center;
                font-size:13px;
                color:#aaa;
                margin-bottom:0;
            }


        </style>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.2/dist/semantic.min.css">
        <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.2/dist/semantic.min.js"></script>

        <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/uicons-regular-rounded/css/uicons-regular-rounded.css'>
    </head>

    <body class="light">
        <header>
            <div class="navbar ">
                <a class ="navbar-brand" href="/">
                    {% load static %}
                    <img src="{% static 'media/ToolioLogoText.png' %}" height="60" class="d-inline-block align-top" alt="">
                </a>
                {% if user.is_authenticated %}
                    <div class="navbar-menu">
                        <a href="/">
                            <i class="fi fi-rr-home" style="color: black; font-size: 2em;"></i>
                        </a>
                        <a href="/createAd/">
                            <i class="fi fi-rr-plus" style="color: black; font-size: 2em;"></i>
                        </a>
                        <a href="{% url 'userPage' user.id %}">
                            <i class="fi fi-rr-user" style="color: black; font-size: 2em;"></i>
                        </a>
                        <div>
                            <input type="checkbox" class="checkbox" id="checkbox">
                            <label for="checkbox" class="checkbox-label" style="margin: 0;">
                                <i class="fa-solid fa-moon"></i>
                                <i class="fa-solid fa-sun"></i>
                            <span class="ball"></span>
                            </label>
                        </div>
                        <p><a href="{% url 'user:logout' %}" class="btn btn-danger">Logg ut</a></p>
                    </div>
                {% else %}
                    <div class="navbar-menu">
                        <a href="{% url 'user:login' %}" class="btn btn-outline-dark">Logg inn</a>
                        <a href="{% url 'user:register' %}" class="btn btn-dark">Registrer deg</a>

                        <div>
                            <input type="checkbox" class="checkbox" id="checkbox">
                            <label for="checkbox" class="checkbox-label" style="margin: 0;">
                                <i class="fa-solid fa-moon"></i>
                                <i class="fa-solid fa-sun"></i>
                            <span class="ball"></span>
                            </label>
                        </div>
                    </div>
                {% endif %}
            </div>
        </header>
        <main class="container">
            {% block content %}
            {% endblock %}
        </main>
        <footer class="footer">
            <ul class="list-inline">
                <li class="list-inline-item"><a href="/">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Toolio © 2023</p>
        </footer>
        </div>
        <script>
            const checkbox = document.getElementById("checkbox")
            // Changes style to whatever mode has been chosen already
            if(localStorage.getItem("mode") == "light") {
                document.body.classList.remove("dark")
                document.body.classList.add("light")
                checkbox.checked = false;
            } else {
                document.body.classList.remove("light")
                document.body.classList.add("dark")
                checkbox.checked = true;
            }

            checkbox.addEventListener("change", () => {
                console.log(checkbox.checked)
                if(document.body.classList.contains("dark")) {
                    document.body.classList.remove("dark")
                    document.body.classList.add("light")
                    localStorage.setItem("mode", "light");
                } else {
                    document.body.classList.remove("light")
                    document.body.classList.add("dark")
                    localStorage.setItem("mode", "dark");
                }
                //document.body.classList.toggle("dark")
                //document.body.classList.toggle("light")    
            })
        </script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

Toolio/main/templates/main/createAd.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Opprett ny annonse{% endblock %}

{% block content %}
<div class="card" style="width: 35rem; margin: auto;">
    <div class="card-body">
        <!-- multipart/form-data allows for sending files throug POST request -->
        <form method="post" enctype="multipart/form-data" class="ui form" style="width: 80%; margin: auto;" id="adForm">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {{ form.source.errors }}
            {{ form.source }}

            <div class="btn-group btn-group-toggle" data-toggle="buttons" style="margin-bottom: 0.7em;">
              <label for="id_type_0" class="btn btn-info active">
                <input type="radio" name="type" value="normalAd" required id="id_type_0" onchange="changeForm(this.id)" checked> Annonse
              </label>
              <label for="id_type_1" class="btn btn-info">
                <input type="radio" name="type" value="requestAd" required id="id_type_1" onchange="changeForm(this.id)"> Ønskes leid
              </label>
            </div>
            

            <div class="field">
              {{ form.title.label_tag }}
              {{ form.title.errors }}
              {{ form.title }}  
            </div>

            <div class="field">
              <label for="id_category">Kategori</label>
              {{ form.category }}
            </div>

            <div class="field">
              <div class="two fields">
                <div class="field">
                  <label for="id_date" id="dateLabel">Produktet er ledig til</label>
                  <div class="ui calendar">
                    <!--<div class="ui input left icon">
                      <i class="calendar icon"></i>-->
                      {{ form.date.errors }}
                      {{ form.date }}
                   <!--</div>-->
                  </div>
                </div>
                <div class="field">
                  <label for="id_price" id="priceLabel">Pris</label>
                  <div class="input-group mb-3" style="flex-wrap: nowrap;">
                    <div class="input-group-prepend">
                      <span class="input-group-text">NOK</span>
                    </div>
                    {{ form.price }}
                    <div class="input-group-append">
                      <span class="input-group-text">.00</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="field">
              {{ form.description.label_tag }}
              {{ form.description.errors }}
              {{ form.description }}
            </div>

            <div class="field" id="imgField">
              {{ form.image.label_tag }}
              {{ form.image.errors }}
              {{ form.image }}
            </div>
            <button type="submit" class="btn btn-success">Legg ut annonse</button>
        </form>
    </div>
</div>

<script>
    function changeForm (radioID){
        const imgField = document.getElementById("imgField");
        
        if (radioID == "id_type_1") {
            document.getElementById("imgField").hidden = "true";
            document.getElementById("priceLabel").innerText = "Budsjett";
            document.getElementById("dateLabel").innerText = "Ønsker å leie til";
        } else {
            document.getElementById("imgField").removeAttribute("hidden");
            document.getElementById("priceLabel").innerHTML = "Pris";
            document.getElementById("dateLabel").innerHTML = "Produktet er ledig til";
        }
    }
</script>

{% endblock %}

Toolio/main/templates/main/popup.html
<h1>This is a pop-up window!</h1>
<p>Click the button to close this window.</p>